### ISSUE TITLE
request token error

### ISSUE THREAD

**Issue by LiesPinket** [skolakoda/programming-quotes-api#30]
Hello, 

I cannot seem to request a token for this API (it keeps giving me an application error for both github and google). Is there a way that I can register so I can obtain a token, or is this closed?

Many thanks in advance.

**Comment by mudroljub** [comment]
I am not sure what is happening, but curently no one working on this API.

**Comment by LiesPinket** [comment]
Ok, thank you for your response.

**Comment by mudroljub** [comment]
No problem, I will leave the issue open, so hopefully some day will fix it.
