### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by adadkins** [skolakoda/programming-quotes-api#34]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

<img width="1645" alt="Screen Shot 2020-02-10 at 3 28 04 PM" src="https://user-images.githubusercontent.com/13097640/74199761-f36b2480-4c19-11ea-91c6-0f33e61d3391.png">

**Comment by pparise** [comment]
Still down as of today.

**Comment by iwaduarte** [comment]
I think the developer dropped this.

**Comment by mudroljub** [comment]
Thanks for reporting. I am a sole developer on this hobby project and I was on vacation last week. I will take a look at this in a next few days.

**Comment by adadkins** [comment]
No problem thanks for fixing.
