### ISSUE TITLE
Application Error Heroku

### ISSUE THREAD

**Issue by iamsahebgiri** [skolakoda/programming-quotes-api#37]
https://programming-quotes-api.herokuapp.com/quotes/random
....
Seems like the api has been broke for some reason.
None of them works.

**Comment by NickNguyeniOS14** [comment]
My app broke guys. The back-end is down. Please help!

**Comment by NickNguyeniOS14** [comment]
My app is on the App Store right now and it's not good :(

**Comment by campbe13** [comment]
503 error after a ~30,000ms timeout

**Comment by apatronl** [comment]
+1, looks like the API is down

**Comment by pparise** [comment]
+1 Still down after a week

**Comment by seidobllik** [comment]
A work around to this API error is to GET the entire JSON object from this repo ([url link here](https://raw.githubusercontent.com/skolakoda/programming-quotes-api/master/backup/quotes.json)), and manipulate it. Here is what I did to my own quote generator:

```

async function getQuote() {
  const url =
    "https://raw.githubusercontent.com/skolakoda/programming-quotes-api/master/backup/quotes.json";
  let response = await fetch(url);
  let json = await response.json();

  json = json[Math.floor(Math.random() * (json.length + 1))];

  return {
    text: json["en"],
    author: json["author"]
  };
}

```

**Comment by NickNguyeniOS14** [comment]
Thanks for your workaround. @seidobllik

**Comment by mudroljub** [comment]
Hello everyone. I am a sole developer of this side project. The problem is, Heroku stops to provide us with a free database. Untill I found some other solution, you can use backup json file, as stated above. 

P.s. Thanks for using this project. I didn't know that anyone still use it untill it broke :)

**Comment by anwa17** [comment]
Would it be possible to use a file db like sqlite or nedb?

**Comment by mudroljub** [comment]
Hello again. 

I rewrote the whole project in C# and deploy it to azurewebsites. I am not sure for how long the free hosting will last, but currently the Programming Quotes API is up and running again :)

Also, you can now POST, PUT, DELETE and more, without any authentification.

Cheers!
