### ISSUE TITLE
Random Endpoint Down

### ISSUE THREAD

**Issue by sergiomoraes** [skolakoda/programming-quotes-api#39]
I believe the [random](https://programming-quotes-api.herokuapp.com/quotes/random) endpoint is currently down.

This is the message I get if I try to load the page directly:

![](https://user-images.githubusercontent.com/21162065/103668404-e808a200-4f2b-11eb-872e-5687a00a5fe7.png)

Edit: I didn't have a chance to check the other links.

**Comment by khenriksson** [comment]
Tried with /quotes as well, same problem.

**Comment by sergiomoraes** [comment]
Same as issue #37, so I'm closing this one. The developer explained the reason for this over there.
