### ISSUE TITLE
Feature: List all authors

### ISSUE THREAD

**Issue by michaelsoliman1** [skolakoda/programming-quotes-api#45]
Hi, I just landed on this repo while searching for an open api to build an app around it (for educational purpose). And I can't seem to find an endpoint to list all authors, If there isn't any, It would be great to add it. 

Update: just found out that you're rewriting the app with .NET, so the endpoint may be there but not yet finished. If that's the case you can ignore this 😅

Thank you for this work it's Awesome!

**Comment by mudroljub** [comment]
Thanks for your Feature request, it is great idea, I can believe I missed it :) I just added it to my TODO list.

**Comment by mudroljub** [comment]
It is implemented :)

**Comment by michaelsoliman1** [comment]
Great! Thank You!
