### ISSUE TITLE
Feture: We can have pictures of authors

### ISSUE THREAD

**Issue by tornikegomareli** [skolakoda/programming-quotes-api#50]
Hello, I am Tornike. Maybe we can add the image URL of the Author in API?

It really makes the user interface of Quote more user-friendly when you can have eye contact with the quote author, that is something different than just reading the text.

Right now I am developing an iOS app for this and I would be very glad if we can add this feature.

**Comment by mudroljub** [comment]
I agree, this is nice to have.

**Comment by mudroljub** [comment]
For now we don't store images, but we could use free images from Wikipedia for most of the authors. I just updated README file with the examples. I hope this will fit your application's need.
